### ISSUE TITLE
Fix broken master build

### ISSUE THREAD

**Issue by jtuttle** [cyberark/conjur-api-ruby#121]
The master branch of the Ruby API is currently failing on an error before the cucumber tests even get run. It's happening because a new version of Cucumber was just released and we do not have the gem version pinned. Pin it back to the latest working version.

**Comment by jtuttle** [comment]
The deprecation warning and stacktrace:

```
Deprecated: Found tags option '~@wip'. Support for '~@tag' will be removed from the next release of Cucumber. Please use 'not @tag' instead.
Expression /^the (?:JSON|json)(?: response)?(?: at "(.*)")? should( not)? be (".*"|\-?\d+(?:\.\d+)?(?:[eE][\+\-]?\d+)?|\[.*\]|%?\{.*\}|true|false|null)$/ has 3 capture groups (["mime_type", nil, "\"application/x-pem-file\""]), but there were 2 parameter types ([".*)\"", " not"]) (Cucumber::CucumberExpressions::CucumberExpressionError)
/usr/local/bundle/gems/cucumber-expressions-4.0.3/lib/cucumber/cucumber_expressions/argument.rb:16:in `build'
/usr/local/bundle/gems/cucumber-expressions-4.0.3/lib/cucumber/cucumber_expressions/regular_expression.rb:43:in `match'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/glue/step_definition.rb:101:in `arguments_from'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/glue/registry_and_more.rb:66:in `block in step_matches'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/glue/registry_and_more.rb:65:in `each'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/glue/registry_and_more.rb:65:in `reduce'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/glue/registry_and_more.rb:65:in `step_matches'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/step_match_search.rb:19:in `call'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/step_match_search.rb:19:in `call'
/usr/local/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/step_match_search.rb:62:in `call'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:66:in `matches'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:47:in `result'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:37:in `find_match'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:33:in `attempt_to_activate'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:29:in `map'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:29:in `new_test_steps'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:23:in `test_case'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:12:in `test_case'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/locations_filter.rb:18:in `block in done'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `each'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `done'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core/filter.rb:62:in `done'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core/compiler.rb:24:in `done'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core/gherkin/parser.rb:37:in `done'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core.rb:32:in `parse'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core.rb:21:in `compile'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:74:in `run!'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/cli/main.rb:33:in `execute!'
/usr/local/bundle/gems/cucumber-3.0.1/bin/cucumber:9:in `<top (required)>'
/usr/local/bundle/bin/cucumber:17:in `load'
/usr/local/bundle/bin/cucumber:17:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```
