### ISSUE TITLE
Tests failing in master on Conjur::API.new_from_key

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur-api-ruby#137]
#### Failing Jenkins Build
https://jenkins.conjur.net/job/cyberark--conjur-api-ruby/job/master/208/

#### Failing Tests

```sh-session
cucumber features/new_api.feature:5 # Scenario: From API key.
cucumber features/new_api.feature:13 # Scenario: From access token.
cucumber features/new_api.feature:24 # Scenario: From access token file.
```

#### Example Test Output
```sh-session
  Scenario: From access token file. # features/new_api.feature:24
    Given I run the code:           # features/step_definitions/api_steps.rb:1
      """
      token = Conjur::API.new_from_key("host/#{@host_id}", @host_api_key).token
      @temp_file = Tempfile.new("token.json")
      @temp_file.write(token.to_json)
      @temp_file.flush
      """
    Then I run the code:            # features/step_definitions/api_steps.rb:1
      """
      api = Conjur::API.new_from_token_file @temp_file.path
      expect(api.resource("cucumber:host:#{@host_id}")).to exist
      """
      expected #<Conjur::Host:0x000055650cbc2778 @id=#<Conjur::Id:0x000055650cbc2c50 @id="cucumber:host:app-515f935a...pocnhaOUc4QUZ5aDRqZ0xURzMwaGp3dmlycjQifQ==\""}, :username=>nil}, @v5_router=Conjur::API::Router::V5> to exist (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/api_steps.rb:2:in `eval'
      (eval):2:in `block in <top (required)>'
      ./features/step_definitions/api_steps.rb:2:in `eval'
      ./features/step_definitions/api_steps.rb:2:in `/^I(?: can)? run the code:$/'
      features/new_api.feature:32:in `Then I run the code:'
```

**Comment by micahlee** [comment]
Fixed in #138
